config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    root "users#index" # Admin start page
    resources :users
    resources :quests, :teachers, :parents, controller: :users
    resources :meetings do
      member do
        get :show_modal
      end
    end  
    resources :meeting_types
  end

  namespace :parent do
    root "parent_meetings#index" # Parent start page
    resources :parent_meetings
    resources :meetings
  end

  resources :meeting_hours
  
  namespace :api do
    namespace :v1 do
      resources :teacher_meetings, only: [:show]
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # # Render dynamic PWA files from app/views/pwa/*
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home_page#index"
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :teacher
  belongs_to :meeting_type, optional: true

  has_many :meeting_hours
  has_many :parent_meetings, dependent: :destroy
  has_many :parents, through: :parent_meetings, source: :parent

  validates :name, :duration, :teacher_id, presence: true
  validate :must_have_at_least_one_meeting_hour

  accepts_nested_attributes_for :meeting_hours, allow_destroy: true
  
  def must_have_at_least_one_meeting_hour
    if meeting_hours.empty?
      errors.add(:meeting_hours, "must have at least one meeting hour")
    end
  end

  def get_meeting_hours
    meeting_hours || build_meeting_hours
  end

  def free_hours
    scheduled_hours = meeting_hours.each_with_object( Hash.new{ |k,v| k[v] = [] }){ |h, o| o[h.day_when] << [h.from_hour, h.to_hour] }
    booked_hours = parent_meetings.each_with_object( Hash.new{ |k,v| k[v] = [] }){ |h, o| o[h.day_when] << h.meeting_hour }
    calculate_free_hours(scheduled_hours, booked_hours)
  end
 
  private

  def calculate_free_hours(scheduled_hours, booked_hours)
    res = {}
    scheduled_hours.each do |day, array_of_hours| 
      booked_hours_for_this_day = booked_hours[day]
      if booked_hours_for_this_day.any?
        booked_hours_for_this_day.each do |el|
          array_of_hours = remove_busy_hours(array_of_hours, el)
        end
      end
      res[day] = array_of_hours   
    end  
    res
  end  

  def remove_busy_hours(array_of_hours, booked_el)
    res = []
    array_of_hours.each do |el|
      puts "??"
      puts el.inspect
      if booked_el.between?(el[0], el[1])
        if (booked_el - el[0]) >= duration.minutes
          res << [el[0], booked_el]
        end

        if (el[1] - (booked_el + duration)) >= duration.minutes
          res << [booked_el + duration.minutes, el[1]]
        end

        next
      end
      res << el
    end
    res
  end
end

app/models/meeting_type.rb
class MeetingType < ApplicationRecord
  has_many :meetings
  validates :name, presence: true
  
  scope :ordered, -> { order(id: :desc) }

  def deletable?
    !meetings.any?
  end
end

app/controllers/admin/meetings_controller.rb
class Admin::MeetingsController < Admin::BaseController
  protect_from_forgery except: :show_modal
  before_action :set_meeting, only: %i[ show edit update destroy show_modal ]
  before_action :load_teachers, only: %i[ new edit update create ]

  def index
    @order = params[:order] || 'teacher'
    if @order == 'no_order'
      @meetings = Meeting.includes(:meeting_hours).paginate(page: params[:page], per_page: 6)
    else
      @meetings = Teacher.includes(meetings: :meeting_hours).order(:email).each_with_object({}) do |teacher, result|
        result[teacher] = teacher.meetings.paginate(page: params["page_#{teacher.id}"], per_page: 2)
      end
    end
  end

  def show
  end

  def show_modal
    render partial: "modal", locals: { meeting: @meeting }
  end

  def new
    @meeting  = Meeting.new
  end

  def create
    @meeting = Meeting.new(meeting_params)

    if @meeting.save
      redirect_to [ :admin, @meeting ], notice: "Meeting was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @meeting.update(meeting_params)
      redirect_to [ :admin, @meeting ], notice: "Meeting was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @meeting.destroy!
    redirect_to meetings_path, status: :see_other, notice: "Meeting was successfully destroyed."
  end

  private

  def load_teachers
    @teachers = Teacher.all
  end

  def set_meeting
    @meeting ||= Meeting.find(params[:id])
  end

  def meeting_params
    params.require(:meeting).permit(:notes, :name, :duration, :teacher_id, :meeting_type_id,
                                    meeting_hours_attributes: [:id, :day_when, :from_hour, :to_hour, :_destroy])
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: %i[ show edit update destroy ]

  # GET /meetings or /meetings.json
  def index
    @meetings = Meeting.all
  end

  # GET /meetings/1 or /meetings/1.json
  def show
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings or /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: "Meeting was successfully created." }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1 or /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: "Meeting was successfully updated." }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1 or /meetings/1.json
  def destroy
    @meeting.destroy!

    respond_to do |format|
      format.html { redirect_to meetings_path, status: :see_other, notice: "Meeting was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def meeting_params
      params.require(:meeting).permit(:notes, :name)
    end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/admin/meetings/_form.html.erb
<%= simple_form_for [:admin, @meeting] do |f| %>
  <% if f.object.errors.any? %>
    <div class="alert alert-danger">
      <h4>There were errors with your meeting:</h4>
      <ul>
        <% f.object.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :teacher_id, as: :select, collection: @teachers.map{ |t| [t.full_name, t.id] } %>
  <%= f.input :name %>
  <%= f.input :meeting_type_id, as: :select, collection: MeetingType.all.map{ |mt| [mt.name, mt.id] } %>
  <%= f.input :notes %>
  <%= f.input :duration %>
  <h3>Meeting Hours</h3>
  <div class="table-responsive-sm">
    <table class="table">
      <thead>
        <tr>
          <th>Day</th>
          <th>Start Hour</th>
          <th>End Hour</th>
          <th>Delete?</th>
        </tr>
      </thead>
      <tbody class='fields'>
        <%= f.simple_fields_for :meeting_hours, @meeting.get_meeting_hours do |mh| %>    
          <%= render 'meeting_hour', f: mh  %>
        <% end %>
      </tbody>
    </table>
  </div>
  <%= link_to_add_row('Add Meeting Hour', f, :meeting_hours, class: "btn btn-secondary") %> 
  </p>
  <div class="d-grid">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/meetings/_meeting.html.erb
<h2 class="accordion-header" id="<%= meeting.id %>">
  <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#<%= dom_id(meeting) %>" aria-expanded="false" aria-controls="<%= dom_id(meeting) %>">
    <%= meeting.name %>
  </button>
</h2>
<div id="<%= dom_id(meeting) %>" class="accordion-collapse collapse <%= 'show' if action_name == 'show' %>" " aria-labelledby="<%= meeting.id %>" data-bs-parent="#meetings">
  <div class="accordion-body">
    <div class="card">
      <div class="card-header">
        <%= meeting.notes %> 
        </p>
        <p>Duration of the meeting <%= meeting.duration %></p>
      </div>
      <div class="card-body">      
           <ul>
            <% meeting.meeting_hours.each do |hour| %> 
              <li >Day <%= hour.day_when %> , start:  <%= hour.from_hour.strftime("%I:%M%p") %>, end:  <%= hour.to_hour.strftime("%I:%M%p") %></li>
            <% end %>
          </ul>
      </div>
    </div>

  </div>
</div>

app/views/admin/meetings/_meeting_hour.html.erb
<tr data-controller="remove-meeting-hour" data-remove-meeting-hour-target="field">
  <td><%= f.date_field :day_when, as: :string, label: "Day" %></td>
  <td><%= f.time_field :from_hour, as: :time, label: "Start Time" %></td>
  <td><%= f.time_field :to_hour, as: :time, label: "End Time" %></td>
  <td>
      <% if f.object.persisted? %>
        <%= f.check_box :_destroy %>
      <% else %>
        <%= link_to 'Remove', '#', class: 'remove_record', data: { action: "click->remove-meeting-hour#remove" } %>
      <% end %>
    </td>
</tr>  

app/views/admin/meetings/_meetings.html.erb
<% meetings.each do |meeting| %>
  <div class="accordion-item">
    <%= render meeting %>
    <p>
      <%= link_to "Show this meeting", admin_meeting_path(meeting), class: 'btn btn-outline-primary' %>
      <%= link_to "Preview this meeting", show_modal_admin_meeting_path(meeting), data: { turbo_frame: "meetingmodal#{meeting.id}" }, class: 'btn btn-outline-secondary' %>
    </p>

    <%= turbo_frame_tag "meetingmodal#{meeting.id}" do %>
    <% end %>
  </div>
<% end %>

app/views/admin/meetings/_modal.html.erb
<%= turbo_frame_tag "meetingmodal#{meeting.id}" do %>
  <div class="modal fade" id="modalmeeting<%= meeting.id %>" tabindex="-1" aria-labelledby="meetingModalLabel" aria-hidden="true" role="dialog">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="meetingModalLabel"><%= meeting.name %></h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p><strong>Notes:</strong> <%= meeting.notes %></p>
          <p><strong>Duration:</strong> <%= meeting.duration %></p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/meetings/edit.html.erb
<% content_for :title, "Editing meeting" %>

<h1>Editing meeting</h1>

<%= render "form", meeting: @meeting %>

<% content_for :sidebar do %>
  <div class="card">
    <div class="card-header">
      Actions
    </div>
    
    <div class="card-body">
      <div class="btn-group-vertical gap-2" role="group" aria-label="Vertical button group">
        <%= link_to "Show this meeting", [:admin, @meeting], class: "btn btn-primary" %>
        <%= link_to "Back to meetings", admin_meetings_path, class: "btn btn-secondary" %>
    </div>
  </div>
<% end %>

app/views/admin/meetings/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Meetings" %>

<div class="accordion" id="meetings">
  <% if @order == 'teacher' %>
      <% @meetings.each do |teacher, teacher_meetings| %>
       <div class="card">
        <div class="card-header">
          <%= teacher&.email %>
        </div>
        <div class="card-body">
          <%= render "meetings", meetings: teacher_meetings.paginate(page: params["page_#{teacher.id}"], per_page: 2) %>
        </div>
        <%= will_paginate teacher_meetings, param_name: "page_#{teacher.id}", renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
        </div>
      <% end %>
  <% else %>
    <%= render "meetings", meetings: @meetings %>
    <%= will_paginate  @meetings , renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
  <% end %>

</div>

<% content_for :sidebar do %>
  <div class="card">
    <div class="card-header">
      Actions
    </div>
    
    <div class="card-body">
      <div class="btn-group-vertical gap-2" role="group" aria-label="Vertical button group">
        <%= link_to "By Teacher", "?order=teacher", class: "btn btn-primary" %>
        <%= link_to "Unsorted scope", "?order=no_order", class: "btn btn-secondary" %>
        <%= link_to "New meeting", new_admin_meeting_path, class: "btn btn-success" %>
    </div>
  </div>
<% end %>

app/views/admin/meetings/new.html.erb
<% content_for :title, "New meeting" %>

<h1>New meeting</h1>

<%= render "form", meeting: @meeting %>

<% content_for :sidebar do %>
  <div class="card">
    <div class="card-header">
      Actions
    </div>
    
    <div class="card-body">
      <div class="btn-group-vertical gap-2" role="group" aria-label="Vertical button group">
        <%= link_to "Back to meetings", admin_meetings_path, class: "btn btn-primary" %>
      </div>
  </div>
<% end %>

app/views/admin/meetings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @meeting %>

<% content_for :sidebar do %>
  <div class="card">
    <div class="card-header">
      Actions
    </div>
    
    <div class="card-body">
      <div class="btn-group-vertical gap-2" role="group" aria-label="Vertical button group">
        <%= link_to "Edit this meeting", edit_admin_meeting_path(@meeting), class: "btn btn-primary" %>
        <%= link_to "Back to meetings", admin_meetings_path, class: "btn btn-secondary" %>
        <%=  button_to "Destroy this meeting", [:admin, @meeting], method: :delete, class: "btn btn-success" %>
    </div>
  </div>
<% end %>