config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    root "users#index" # Admin start page
    resources :users
    resources :quests, :teachers, :parents, controller: :users
    resources :meetings do
      member do
        get :show_modal
      end
    end  
    resources :meeting_types
  end

  namespace :parent do
    root "parent_meetings#index" # Parent start page
    resources :parent_meetings
    resources :meetings
  end

  resources :meeting_hours
  
  namespace :api do
    namespace :v1 do
      resources :teacher_meetings, only: [:show]
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # # Render dynamic PWA files from app/views/pwa/*
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home_page#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  before_create :set_default_role

  scope :regular, -> { where.not(type: "Admin") }

  def set_default_role
    self.type ||= "Quest"
  end

  def admin?
    type == "Admin"
  end

  def teacher?
    type == "Teacher"
  end

  def student?
    type == "Student"
  end

  def quest?
    type == "Quest"
  end

  def parent?
    type == "Parent"
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def after_database_authentication
    update_column(:last_login_at, Time.current)
    REDIS.set("user:last_login_at:#{id}", Time.current.to_s)
  end

  def last_access
    stored_time = REDIS.get("user:last_login_at:#{id}")
    stored_time.present? ? Time.parse(stored_time) : self[:last_login_at]
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
    before_action :find_users, only: :index

    def index
    end

    def edit
    end

    def show
    end

    def update
      if current_user_to_edit.update(user_params)
        redirect_to admin_users_path
      else
        render :edit
      end
    end

    def destroy
      current_user_to_edit.destroy
    end

    protected

    helper_method def current_user_to_edit
      @current_user_to_edit = User.find(params[:id])
    end

    private

    def user_params
      temp_param = params.require(current_user_to_edit.type.downcase.to_sym).permit(:first_name, :last_name, :type)

      temp_param.delete(:type) if temp_param[:type] == "Admin"

      temp_param
    end

    def find_users
      @teachers ||= Teacher.all
      @quests   ||= Quest.all
      @parents  ||= Parent.all
    end
end

app/views/admin/users/_form.html.erb
<%= simple_form_for [:admin, current_user_to_edit] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :type, as: :select, collection: ['Quest', 'Teacher', 'Student', 'Parent'], selected: f.object.type %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/admin/users/_glance.erb
<div id="<%= dom_id current_user_to_edit %>">
  <p>
    <strong>Full name:</strong>
    <%= current_user_to_edit.full_name %>
  </p>

  <p>
    <strong>Role:</strong>
    <%= current_user_to_edit.type %>
  </p>

</div>

app/views/admin/users/_user_row.html.erb
<tr>
  <td><%= user.first_name %></td>
  <td><%= user.last_name %></td>
  <td><%= user.type %></td>
  <td><%= user.last_access %></td>
  <td>
    <%= link_to "edit", edit_admin_user_path(user) %>
    <%= link_to "delete", '#' %>
  </td>
</tr>

app/views/admin/users/edit.html.erb
<% content_for :title, "Editing user" %>

<h1>Editing User</h1>

<%= render "form" %>

<br>

<div>
  <%= link_to "Show this user", admin_user_path(current_user_to_edit) %> |
  <%= link_to "Back to users", admin_users_path %>
</div>

app/views/admin/users/index.html.erb
<% content_for :title, "Users" %>
<% headings = capture do%>
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Role</th>
    <th>Last Login</th>
    <th>Actions</th>
  </tr>
<% end %>

</p>
<h2>Teachers</h2>
<table class="table uniform-table">
  <thead>
    <%= headings %>
  </thead>
  <tbody>
    <% @teachers.each do |user| %>
      <%= render "user_row", user: user %>
    <% end %>
  </tbody>
</table>

<h2>Parents</h2>
<table class="table uniform-table">
  <thead>
    <%= headings %>
  </thead>
  <tbody>
    <% @parents.each do |user| %>
      <%= render "user_row", user: user %>
    <% end %>
  </tbody>
</table>

<h2>Quests</h2>
<table class="table uniform-table">
  <thead>
    <%= headings %>
  </thead>
  <tbody>
    <% @quests.each do |user| %>
      <%= render "user_row", user: user %>
    <% end %>
  </tbody>
</table>

app/views/admin/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render "glance" %>

<div>
  <%= link_to "Edit this user", edit_admin_user_path(current_user_to_edit) %> |
  <%= link_to "Back to users", admin_users_path %>

  <%= button_to "Destroy this user", polymorphic_path([:admin, current_user_to_edit]), method: :delete %>
</div>