config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    root "users#index" # Admin start page
    resources :users
    resources :quests, :teachers, :parents, controller: :users
    resources :meetings do
      member do
        get :show_modal
      end
    end  
    resources :meeting_types
  end

  namespace :parent do
    root "parent_meetings#index" # Parent start page
    resources :parent_meetings
    resources :meetings
  end

  resources :meeting_hours
  
  namespace :api do
    namespace :v1 do
      resources :teacher_meetings, only: [:show]
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # # Render dynamic PWA files from app/views/pwa/*
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home_page#index"
end

app/models/meeting_hour.rb
class MeetingHour < ApplicationRecord
  belongs_to :meeting

  validates :day_when, :from_hour, :to_hour, presence: true
  validate :hours

  def hours
    return if from_hour.nil? || to_hour.nil?

    if from_hour > to_hour
      errors.add(:base, "start hour must be before end hour")
    end
    if (to_hour - from_hour) < meeting.duration*60
      errors.add(:base, "Time between hours is shorter than meeting duration")
    end
    other_hours = meeting.meeting_hours.reject { |hour| hour == self }
    if other_hours.any? { |hour| same_day_overlap?(hour) }
      errors.add(:base, "Time between hours is overlapping")
    end
  end
  
  def same_day_overlap?(other_hour)
    other_hour.day_when == day_when && boundaries.overlaps?(other_hour.boundaries)
  end

  def boundaries
    from_hour..to_hour
  end
end

app/controllers/meeting_hours_controller.rb
class MeetingHoursController < ApplicationController
  # before_action :set_meeting_hour, only: %i[ show edit update destroy ]

  # # GET /meeting_hours or /meeting_hours.json
  # def index
  #   @meeting_hours = MeetingHour.all
  # end

  # # GET /meeting_hours/1 or /meeting_hours/1.json
  # def show
  # end

  # # GET /meeting_hours/new
  # def new
  #   @meeting_hour = MeetingHour.new
  # end

  # # GET /meeting_hours/1/edit
  # def edit
  # end

  # # POST /meeting_hours or /meeting_hours.json
  # def create
  #   @meeting_hour = MeetingHour.new(meeting_hour_params)

  #   respond_to do |format|
  #     if @meeting_hour.save
  #       format.html { redirect_to @meeting_hour, notice: "Meeting hour was successfully created." }
  #       format.json { render :show, status: :created, location: @meeting_hour }
  #     else
  #       format.html { render :new, status: :unprocessable_entity }
  #       format.json { render json: @meeting_hour.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # PATCH/PUT /meeting_hours/1 or /meeting_hours/1.json
  # def update
  #   respond_to do |format|
  #     if @meeting_hour.update(meeting_hour_params)
  #       format.html { redirect_to @meeting_hour, notice: "Meeting hour was successfully updated." }
  #       format.json { render :show, status: :ok, location: @meeting_hour }
  #     else
  #       format.html { render :edit, status: :unprocessable_entity }
  #       format.json { render json: @meeting_hour.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /meeting_hours/1 or /meeting_hours/1.json
  # def destroy
  #   @meeting_hour.destroy!

  #   respond_to do |format|
  #     format.html { redirect_to meeting_hours_path, status: :see_other, notice: "Meeting hour was successfully destroyed." }
  #     format.json { head :no_content }
  #   end
  # end

  # private
  #   # Use callbacks to share common setup or constraints between actions.
  #   def set_meeting_hour
  #     @meeting_hour = MeetingHour.find(params[:id])
  #   end

  #   # Only allow a list of trusted parameters through.
  #   def meeting_hour_params
  #     params.require(:meeting_hour).permit(:from, :to, :, :day, :, :metting_id)
  #   end
end

app/helpers/meeting_hours_helper.rb
module MeetingHoursHelper
end

app/views/meeting_hours/_form.html.erb
<%= form_with(model: meeting_hour) do |form| %>
  <% if meeting_hour.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(meeting_hour.errors.count, "error") %> prohibited this meeting_hour from being saved:</h2>

      <ul>
        <% meeting_hour.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :from, style: "display: block" %>
    <%= form.time_field :from %>
  </div>

  <div>
    <%= form.label :to, style: "display: block" %>
    <%= form.text_field :to %>
  </div>

  <div>
    <%= form.label :, style: "display: block" %>
    <%= form.time_field : %>
  </div>

  <div>
    <%= form.label :day, style: "display: block" %>
    <%= form.text_field :day %>
  </div>

  <div>
    <%= form.label :, style: "display: block" %>
    <%= form.date_field : %>
  </div>

  <div>
    <%= form.label :metting_id, style: "display: block" %>
    <%= form.text_field :metting_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/meeting_hours/_meeting_hour.html.erb
<div id="<%= dom_id meeting_hour %>">
  <p>
    <strong>From:</strong>
    <%= meeting_hour.from %>
  </p>

  <p>
    <strong>To:</strong>
    <%= meeting_hour.to %>
  </p>

  <p>
    <strong>:</strong>
    <%= meeting_hour. %>
  </p>

  <p>
    <strong>Day:</strong>
    <%= meeting_hour.day %>
  </p>

  <p>
    <strong>:</strong>
    <%= meeting_hour. %>
  </p>

  <p>
    <strong>Metting:</strong>
    <%= meeting_hour.metting_id %>
  </p>

</div>

app/views/meeting_hours/edit.html.erb
<% content_for :title, "Editing meeting hour" %>

<h1>Editing meeting hour</h1>

<%= render "form", meeting_hour: @meeting_hour %>

<br>

<div>
  <%= link_to "Show this meeting hour", @meeting_hour %> |
  <%= link_to "Back to meeting hours", meeting_hours_path %>
</div>

app/views/meeting_hours/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Meeting hours" %>

<h1>Meeting hours</h1>

<div id="meeting_hours">
  <% @meeting_hours.each do |meeting_hour| %>
    <%= render meeting_hour %>
    <p>
      <%= link_to "Show this meeting hour", meeting_hour %>
    </p>
  <% end %>
</div>

<%= link_to "New meeting hour", new_meeting_hour_path %>

app/views/meeting_hours/new.html.erb
<% content_for :title, "New meeting hour" %>

<h1>New meeting hour</h1>

<%= render "form", meeting_hour: @meeting_hour %>

<br>

<div>
  <%= link_to "Back to meeting hours", meeting_hours_path %>
</div>

app/views/meeting_hours/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @meeting_hour %>

<div>
  <%= link_to "Edit this meeting hour", edit_meeting_hour_path(@meeting_hour) %> |
  <%= link_to "Back to meeting hours", meeting_hours_path %>

  <%= button_to "Destroy this meeting hour", @meeting_hour, method: :delete %>
</div>