config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    root "users#index" # Admin start page
    resources :users
    resources :quests, :teachers, :parents, controller: :users
    resources :meetings do
      member do
        get :show_modal
      end
    end  
    resources :meeting_types
  end

  namespace :parent do
    root "parent_meetings#index" # Parent start page
    resources :parent_meetings
    resources :meetings
  end

  resources :meeting_hours
  
  namespace :api do
    namespace :v1 do
      resources :teacher_meetings, only: [:show]
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # # Render dynamic PWA files from app/views/pwa/*
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home_page#index"
end

app/views/layouts/_admin.html.erb
<div class="container">
  <div class="row mb-4">
    <div class="col-12">
      <%= yield :title %>
    </div>
  </div>
  
  <div class="row">
    <div class="col-md-9 mb-3">
      <ul class="nav nav-tabs">
        <li class="nav-item">
          <%= link_to 'Users', admin_users_path, class: "nav-link #{'active' if controller_name == 'users'}" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Meetings', admin_meetings_path, class: "nav-link #{'active' if controller_name == 'meetings'}" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Meeting Types', admin_meeting_types_path, class: "nav-link #{'active' if controller_name == 'meeting_types'}" %>
        </li>
      </ul>

      <div class="content">
        <%= yield %>
      </div>
    </div>

    <div class="col-md-3">
       <% if (sidebar = yield :sidebar).present? %>
        <div class="card">
          <%= sidebar %>
        </div>
       <% end %> 
    </div>
  </div>
</div>

app/views/layouts/_parent.html.erb
<div class="container">
  <div class="row mb-4">
    <div class="col-12">
      <%= yield :title %>
    </div>
  </div>
  
  <div class="row">
    <div class="col-md-9 mb-3">

      <div class="content">
        <%= yield %>
      </div>
    </div>

    <div class="col-md-3">
      <%= yield :sidebar %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= "Teacher Booking App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", type: "module", "data-turbo-track": "reload", defer: true %>
    <script type="module" src="<%= asset_path('application.js') %>"></script>
  </head>

  <body>
    <% if user_signed_in? %>
      <div class="row g-0">
        <div class="col-sm-6 col-md-10">
          <div class="card">
            <div class="card-body">
              Welcome <%= current_user.email %>
            </div>
          </div>
        </div>
        <div class="col-6 col-md-2">
          <div class="card">
            <div class="card-body">
              <%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete } %>
            </div>
          </div>
        </div>
      </div>
    <% else %>
      <%= button_to "Sign in", new_user_session_path %>
    <% end %>

    <% if current_user&.admin? %>  
      <%= render layout: 'layouts/admin' do %>
        <%= yield %>
      <% end %>
    <% elsif current_user&.parent? %>  
      <%= render layout: 'layouts/parent' do %>
        <%= yield %>
      <% end %>   
    <% else %>
      <%= yield %>
    <% end %>  

    <div id="dynamic-modal-point"></div>
  </body>
</html>